name: Python package

# on:
#   delete
on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Install
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest coverage
        pip install .
    - name: Test with pytest, via coverage
      run: coverage run -m pytest
    - name: Upload coverage report to Codecov
      uses: codecov/codecov-action@v3